name: Run Script in Shifts

on:
  schedule:
    - cron: "0 3 * * *"   # 8:30 AM IST (03:00 UTC)
    - cron: "0 9 * * *"   # 2:30 PM IST (09:00 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 6 hours per run
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python __main__.py
